/**
 * BSD-YBM AI Solutions — PDF / export utilities (tenant colors from payload / CSS).
 * Uses jsPDF + html2canvas (via jsPDF html plugin) for RTL Hebrew via DOM + system fonts.
 */

import { PLATFORM_BRANDING } from '@/lib/platformOwners';
import type { ExecutiveFinanceReportPayload, ProjectStatusReportPayload } from '@/services/reports/types';

const BRAND_BLUE = '#001A4D';
const BRAND_ORANGE = '#FF7F00';
const PAGE_BG = '#FDFDFD';

function escapeAttr(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
}

/** Golden Helix (image_8) or tenant logo for PDF/HTML headers. */
function reportHeaderLogoBlock(headerLogoUrl?: string | null): string {
  const tenant = headerLogoUrl?.trim();
  if (tenant) {
    return `<div style="display:flex;align-items:center;justify-content:center;gap:12px;margin-bottom:12px">
  <img src="${escapeAttr(tenant)}" alt="" width="160" height="56" style="max-height:56px;width:auto;object-fit:contain" crossorigin="anonymous" />
</div>`;
  }
  return `<div style="display:flex;align-items:center;justify-content:center;gap:12px;margin-bottom:12px">
  <img src="/image_8.svg" width="48" height="48" alt="" style="object-fit:contain;flex-shrink:0" />
  <div style="text-align:center">
    <div style="font-size:13px;font-weight:800;color:${BRAND_BLUE}">${PLATFORM_BRANDING.legalName}</div>
    <div style="font-size:10px;font-weight:700;color:${BRAND_ORANGE};margin-top:2px">AI Solutions</div>
  </div>
</div>`;
}

function cardStyle(): string {
  return [
    'background:#FFFFFF',
    'border:2px solid ' + BRAND_ORANGE,
    'border-radius:32px',
    'padding:20px 24px',
    'margin:0 auto 16px',
    'max-width:720px',
    'box-sizing:border-box',
    'text-align:center',
  ].join(';');
}

function sectionTitle(text: string): string {
  return `<h2 style="margin:0 0 12px;font-size:15px;font-weight:800;color:${BRAND_BLUE};letter-spacing:0.02em">${text}</h2>`;
}

function buildShell(inner: string, title: string, subtitle: string, headerLogoUrl?: string | null): string {
  const safePad = 'padding:calc(20px + env(safe-area-inset-top,0px)) calc(20px + env(safe-area-inset-right,0px)) calc(24px + env(safe-area-inset-bottom,0px)) calc(20px + env(safe-area-inset-left,0px))';
  return `
<!DOCTYPE html><html lang="he" dir="rtl"><head><meta charset="utf-8"/>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;700;800&display=swap" rel="stylesheet"/>
<style>
  * { box-sizing:border-box; }
  body { margin:0; font-family:'Heebo',Arial,sans-serif; background:${PAGE_BG}; color:#1a1a1a; ${safePad}; }
</style></head><body>
  <div style="${cardStyle()}">
    ${reportHeaderLogoBlock(headerLogoUrl)}
    <h1 style="margin:0;font-size:22px;font-weight:800;color:${BRAND_BLUE}">${title}</h1>
    <p style="margin:12px 0 0;font-size:12px;color:#64748b">${subtitle}</p>
  </div>
  ${inner}
  <div style="text-align:center;font-size:10px;color:#94a3b8;margin-top:20px">דוח פנימי לניהול · לא מהווה ייעוץ מס</div>
  <div style="text-align:center;font-size:9px;color:#64748b;margin-top:12px;line-height:1.6">
    Generated by ${PLATFORM_BRANDING.legalName} | ${PLATFORM_BRANDING.chairman} | <a href="${PLATFORM_BRANDING.website}" style="color:${BRAND_BLUE};font-weight:700;text-decoration:underline">${PLATFORM_BRANDING.websiteDisplay}</a>
  </div>
</body></html>`;
}

export function buildProjectStatusReportHtml(p: ProjectStatusReportPayload): string {
  const fin = p.financial;
  const inner = `
  <div style="${cardStyle()}">
    ${sectionTitle('סיכום פיננסי — תקציב מול ביצוע')}
    <table style="width:100%;border-collapse:separate;border-spacing:0 8px;font-size:13px">
      <tr><td style="font-weight:700;color:#475569">תקציב</td><td style="font-weight:800;color:${BRAND_BLUE}">${fin.budget.toLocaleString('he-IL')} ₪</td></tr>
      <tr><td style="font-weight:700;color:#475569">ביצוע (עבודה + חומר)</td><td style="font-weight:800;color:${BRAND_BLUE}">${fin.actual.toLocaleString('he-IL')} ₪</td></tr>
      <tr><td style="font-weight:700;color:#475569">שונות</td><td style="font-weight:800;color:${fin.variance >= 0 ? '#b45309' : BRAND_ORANGE}">${fin.variance.toLocaleString('he-IL')} ₪</td></tr>
      <tr><td style="font-weight:700;color:#475569">עלות עבודה</td><td>${fin.laborCosts.toLocaleString('he-IL')} ₪</td></tr>
      <tr><td style="font-weight:700;color:#475569">עלות חומר</td><td>${fin.materialCosts.toLocaleString('he-IL')} ₪</td></tr>
    </table>
  </div>
  <div style="${cardStyle()}">
    ${sectionTitle('אבני דרך שהושלמו')}
    ${
      p.completedMilestones.length === 0
        ? '<p style="margin:0;font-size:13px;color:#64748b">אין אבני דרך מסומנות כהושלמו</p>'
        : `<ul style="margin:0;padding:0;list-style:none;text-align:center">
          ${p.completedMilestones.map((m) => `<li style="margin:8px 0;font-size:13px"><span style="color:${BRAND_ORANGE}">★</span> ${m.title} <span style="color:#94a3b8">· יעד ${m.targetDate || '—'}</span></li>`).join('')}
        </ul>`
    }
  </div>
  <div style="${cardStyle()}">
    ${sectionTitle('ציר זמן — תצוגת לקוח (אחרונים)')}
    ${
      p.clientTimeline.length === 0
        ? '<p style="margin:0;font-size:13px;color:#64748b">אין פריטים להצגה</p>'
        : `<ul style="margin:0;padding:0;list-style:none">
          ${p.clientTimeline
            .map(
              (e) =>
                `<li style="margin:12px 0;padding:12px;border-radius:32px;background:#FDFDFD;border:1px solid #e2e8f0;text-align:center">
                  <div style="font-weight:800;font-size:12px;color:${BRAND_BLUE}">${e.title}</div>
                  <div style="font-size:12px;color:#334155;margin-top:6px">${e.subtitle}</div>
                  <div style="font-size:10px;color:#94a3b8;margin-top:6px">${e.when}</div>
                </li>`
            )
            .join('')}
        </ul>`
    }
  </div>`;

  const gen = new Date(p.generatedAtIso).toLocaleString('he-IL');
  return buildShell(
    inner,
    'דוח סטטוס פרויקט',
    `${p.projectName} · מזהה ${p.projectId} · נוצר ${gen}`,
    p.headerLogoUrl
  );
}

export function buildExecutiveFinanceReportHtml(p: ExecutiveFinanceReportPayload): string {
  const rows =
    p.projects.length === 0
      ? '<p style="margin:0;font-size:13px;color:#64748b">אין פרויקטים בטעינה</p>'
      : `<table style="width:100%;border-collapse:collapse;font-size:12px;margin-top:8px">
        <thead><tr style="background:${BRAND_BLUE};color:#fff">
          <th style="padding:10px;border-radius:32px 0 0 0">פרויקט</th>
          <th style="padding:10px">תקציב</th>
          <th style="padding:10px;border-radius:0 32px 0 0">ביצוע</th>
        </tr></thead>
        <tbody>
          ${p.projects
            .map(
              (r, i) => `<tr style="background:${i % 2 === 0 ? '#fff' : '#f8fafc'}">
            <td style="padding:10px;text-align:center;font-weight:700">${r.name}</td>
            <td style="padding:10px;text-align:center">${r.budgeted.toLocaleString('he-IL')} ₪</td>
            <td style="padding:10px;text-align:center">${r.actual.toLocaleString('he-IL')} ₪</td>
          </tr>`
            )
            .join('')}
        </tbody>
      </table>`;

  const inner = `
  <div style="${cardStyle()}">
    ${sectionTitle('מדדי חברה')}
    <table style="width:100%;border-collapse:separate;border-spacing:0 8px;font-size:14px">
      <tr><td style="font-weight:700">הכנסות</td><td style="font-weight:800;color:${BRAND_ORANGE}">${p.revenue.toLocaleString('he-IL')} ₪</td></tr>
      <tr><td style="font-weight:700">הוצאות (פרויקטים)</td><td style="font-weight:800;color:${BRAND_BLUE}">${p.expenses.toLocaleString('he-IL')} ₪</td></tr>
      <tr><td style="font-weight:700">רווח נקי</td><td style="font-weight:800;color:${p.netProfit >= 0 ? BRAND_ORANGE : '#b91c1c'}">${p.netProfit.toLocaleString('he-IL')} ₪</td></tr>
    </table>
  </div>
  <div style="${cardStyle()}">${sectionTitle('בריאות פרויקטים')}${rows}</div>`;

  const gen = new Date(p.generatedAtIso).toLocaleString('he-IL');
  return buildShell(inner, 'דוח מנהלים — פיננסים', `חברה ${p.companyId.slice(0, 8)}… · נוצר ${gen}`, p.headerLogoUrl);
}

export type SignedContractPdfMeta = {
  /** Filled contract body (HTML fragment). */
  bodyHtml: string;
  signatureDataUrl: string;
  signedAtIso: string;
  ip: string;
  signerEmail?: string;
  projectName: string;
  companyDisplayName: string;
  /** Tenant logo for PDF header; else Golden Helix. */
  headerLogoUrl?: string | null;
};

/** Final PDF HTML for e-signed project agreements (RTL). */
export function buildSignedContractPdfHtml(m: SignedContractPdfMeta): string {
  const inner = `
  <div style="${cardStyle()}">
    ${sectionTitle('תוכן ההסכם')}
    <div style="text-align:right;font-size:13px;line-height:1.75;color:#1e293b">${m.bodyHtml}</div>
  </div>
  <div style="${cardStyle()}">
    ${sectionTitle('חתימה דיגיטלית')}
    <div style="text-align:center">
      <img src="${m.signatureDataUrl.replace(/"/g, '&quot;')}" alt="" style="max-width:260px;max-height:120px;margin:8px auto;display:block;object-fit:contain" />
      <p style="margin:8px 0 0;font-size:11px;color:#64748b">נחתם ב־${escapeAttr(m.signedAtIso)}</p>
      <p style="margin:4px 0 0;font-size:11px;color:#64748b">כתובת IP: ${escapeAttr(m.ip)}${m.signerEmail ? ` · ${escapeAttr(m.signerEmail)}` : ''}</p>
      <p style="margin:8px 0 0;font-size:10px;color:#94a3b8">${escapeAttr(m.companyDisplayName)} · ${escapeAttr(m.projectName)}</p>
    </div>
  </div>`;
  return buildShell(
    inner,
    'הסכם פרויקט חתום',
    'מסמך משפטי — שמור לצורכי ביקורת · BSD-YBM AI Solutions',
    m.headerLogoUrl
  );
}

export type QuoteSignedPdfMeta = {
  quoteTitle: string;
  lines: { label: string; amount: number }[];
  total: number;
  signatureDataUrl: string;
  signedAtIso: string;
  ip: string;
  signerEmail?: string;
  projectName: string;
  companyDisplayName: string;
  headerLogoUrl?: string | null;
};

export function buildQuoteSignedPdfHtml(m: QuoteSignedPdfMeta): string {
  const rows =
    m.lines.length === 0
      ? '<p style="margin:0;font-size:13px;color:#64748b">אין שורות</p>'
      : `<table style="width:100%;border-collapse:collapse;font-size:13px;margin-top:8px">
        ${m.lines
          .map(
            (r, i) =>
              `<tr style="background:${i % 2 === 0 ? '#fff' : '#f8fafc'}">
            <td style="padding:10px;text-align:right;font-weight:700">${escapeAttr(r.label)}</td>
            <td style="padding:10px;text-align:center">${r.amount.toLocaleString('he-IL')} ₪</td>
          </tr>`
          )
          .join('')}
        </table>`;
  const inner = `
  <div style="${cardStyle()}">
    ${sectionTitle('הצעת מחיר מאושרת')}
    <p style="margin:0 0 8px;font-size:14px;font-weight:800;color:${BRAND_BLUE}">${escapeAttr(m.quoteTitle)}</p>
    <p style="margin:0;font-size:12px;color:#64748b">${escapeAttr(m.projectName)} · ${escapeAttr(m.companyDisplayName)}</p>
    ${rows}
    <p style="margin:12px 0 0;font-size:15px;font-weight:800;color:${BRAND_ORANGE}">סה״כ: ${m.total.toLocaleString('he-IL')} ₪</p>
  </div>
  <div style="${cardStyle()}">
    ${sectionTitle('אישור חתימה')}
    <div style="text-align:center">
      <img src="${m.signatureDataUrl.replace(/"/g, '&quot;')}" alt="" style="max-width:260px;max-height:120px;margin:8px auto;display:block;object-fit:contain" />
      <p style="margin:8px 0 0;font-size:11px;color:#64748b">נחתם ב־${escapeAttr(m.signedAtIso)}</p>
      <p style="margin:4px 0 0;font-size:11px;color:#64748b">IP: ${escapeAttr(m.ip)}${m.signerEmail ? ` · ${escapeAttr(m.signerEmail)}` : ''}</p>
    </div>
  </div>`;
  return buildShell(inner, 'הצעת מחיר חתומה', 'מסמך משפטי — BSD-YBM AI Solutions', m.headerLogoUrl);
}

export async function renderQuoteSignedPdfBlob(m: QuoteSignedPdfMeta): Promise<Blob> {
  const html = buildQuoteSignedPdfHtml(m);
  return renderHtmlToPdfBlob(html);
}

export async function renderHtmlToPdfBlob(html: string): Promise<Blob> {
  const host = document.createElement('div');
  host.setAttribute('dir', 'rtl');
  host.style.cssText = [
    'position:fixed',
    'left:0',
    'top:0',
    'width:794px',
    'z-index:-9999',
    'opacity:0.001',
    'pointer-events:none',
    'overflow:visible',
  ].join(';');
  host.innerHTML = html;
  document.body.appendChild(host);

  try {
    await document.fonts.ready;
    await new Promise<void>((r) => requestAnimationFrame(() => r()));

    const { jsPDF } = await import('jspdf');
    const pdf = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4', compress: true });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 8;

    await pdf.html(host, {
      x: margin,
      y: margin,
      width: pageWidth - margin * 2,
      windowWidth: 794,
      autoPaging: 'slice',
      html2canvas: {
        scale: 0.72,
        useCORS: true,
        logging: false,
        scrollY: 0,
        scrollX: 0,
      },
    });

    return pdf.output('blob');
  } finally {
    document.body.removeChild(host);
  }
}

export async function downloadProjectStatusPdf(p: ProjectStatusReportPayload, fileBase?: string): Promise<void> {
  const html = buildProjectStatusReportHtml(p);
  const blob = await renderHtmlToPdfBlob(html);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileBase ?? 'project-status'}-${p.projectId.slice(0, 8)}.pdf`;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function downloadExecutiveFinancePdf(p: ExecutiveFinanceReportPayload, fileBase?: string): Promise<void> {
  const html = buildExecutiveFinanceReportHtml(p);
  const blob = await renderHtmlToPdfBlob(html);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileBase ?? 'executive-finance'}-${new Date().toISOString().slice(0, 10)}.pdf`;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function renderSignedContractPdfBlob(m: SignedContractPdfMeta): Promise<Blob> {
  const html = buildSignedContractPdfHtml(m);
  return renderHtmlToPdfBlob(html);
}
